# Portalkeeper example realm configuration
#
# Copy this file and provide values appropriate for your realm.
# Do not store private realm configurations in a public repository.

[Server]
Name=Example Realm
Address=realm.example.com

[Updates]
ManifestURL=
NewsURL=
StatusURL=